#!/bin/bash
txt() { cat<<EOF
From: 	icsme2016-artifacts@easychair.org
Subject: Registration, ICSME'16 artifacts track for $1

Dear $1

Thank you for submission! Please note the following
next steps (taken from our CFP). If you have any
technical issues with the following (e.g., you are not
familiar with using GitHub) then please contact us and
we will do the following for you.

1) ICSME-16 Artifacts GitHub repository:

https://github.com/researchart/icsme16

2) Your directory for submissions:

https://github.com/researchart/icmse16/tree/master/submissions/$1

3) Drag and drop your PDF onto that directory.

4) Create an issue in that repository whose title is the
XXX_YYY. Do not add any text to the comment.

Regards,

Olga & Tim
EOF
}

mkdir submissions/$1
touch submissions/$1/README.md
git add submissions/$1/README.md
git commit -am "Registering an author to the repo"
git push origin master

txt $1 $2
txt $1  $2| /usr/sbin/sendmail -t $2 icsme2016-artifacts@easychair.org
